In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

corruptedData = pd.read_csv('eksikveriler.csv')
print(corruptedData)

   ulke  boy  kilo   yas cinsiyet
0    tr  130    30  10.0        e
1    tr  125    36  11.0        e
2    tr  135    34  10.0        k
3    tr  133    30   9.0        k
4    tr  129    38  12.0        e
5    tr  180    90  30.0        e
6    tr  190    80  25.0        e
7    tr  175    90  35.0        e
8    tr  177    60  22.0        k
9    us  185   105  33.0        e
10   us  165    55  27.0        k
11   us  155    50  44.0        k
12   us  160    58   NaN        k
13   us  162    59  41.0        k
14   us  167    62  55.0        k
15   fr  174    70  47.0        e
16   fr  193    90   NaN        e
17   fr  187    80  27.0        e
18   fr  183    88  28.0        e
19   fr  159    40  29.0        k
20   fr  164    66  32.0        k
21   fr  166    56  42.0        k


In [5]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
age = corruptedData.iloc[:, 1:4].values

imputer = imputer.fit(age[:, 1:4])
age[:, 1:4] = imputer.transform(age[:, 1:4])
print(age)

country = corruptedData.iloc[:, 0:1].values
print(country)

[[130.    30.    10.  ]
 [125.    36.    11.  ]
 [135.    34.    10.  ]
 [133.    30.     9.  ]
 [129.    38.    12.  ]
 [180.    90.    30.  ]
 [190.    80.    25.  ]
 [175.    90.    35.  ]
 [177.    60.    22.  ]
 [185.   105.    33.  ]
 [165.    55.    27.  ]
 [155.    50.    44.  ]
 [160.    58.    28.45]
 [162.    59.    41.  ]
 [167.    62.    55.  ]
 [174.    70.    47.  ]
 [193.    90.    28.45]
 [187.    80.    27.  ]
 [183.    88.    28.  ]
 [159.    40.    29.  ]
 [164.    66.    32.  ]
 [166.    56.    42.  ]]
[['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['us']
 ['us']
 ['us']
 ['us']
 ['us']
 ['us']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']]


In [9]:
from sklearn import preprocessing
import pandas as pd

# Assuming 'corruptedData' is already loaded with your dataset
# Label encoding the 'country' column
le = preprocessing.LabelEncoder()

country = corruptedData.iloc[:, 0:1].values
country[:, 0] = le.fit_transform(corruptedData.iloc[:, 0])
print(country)

# One-hot encoding the 'country' column
ohe = preprocessing.OneHotEncoder()
country = ohe.fit_transform(country).toarray()
print(country)

# Convert the encoded data into a DataFrame
sonuc = pd.DataFrame(data=country, index=range(len(country)), columns=['fr', 'tr', 'us'])
print(sonuc)

# Create DataFrame for 'age'
age = corruptedData.iloc[:, 1:4].values
sonuc2 = pd.DataFrame(data=age, index=range(len(age)), columns=['boy', 'kilo', 'yas'])
print(sonuc2)

# Encode 'cinsiyet' column directly
cinsiyet = corruptedData.iloc[:, -1].replace({'e': 1, 'k': 0}).values
print(cinsiyet)

# Convert 'cinsiyet' into a DataFrame
sonuc3 = pd.DataFrame(data=cinsiyet, index=range(len(cinsiyet)), columns=['cinsiyet'])
print(sonuc3)

# Concatenate the DataFrames
s = pd.concat([sonuc, sonuc2], axis=1)
print(s)

s = pd.concat([s, sonuc3], axis=1)
print(s)


[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
     fr   tr   us
0   0.0  1.0  0.0
1   0.0  1.0  0.0
2   0.0  1.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   0.0  1.0  0.0
7   0.0  1.0  0.0
8   0.0  1.0  0.0
9   0.0  0.0  1.0
10  0.0  0.0  1.0
11  0.0  0.0  1.0
12  0.0  0.0  1.0
13  0.0  0.0  1.0
14  0.0  0.0  1.0
15  1.0  0.0  0.0
16  1.0  0.0  0.0
17  1.0  0.0  0.0
18  1.0  0.0  0.0
19  1.0  0.0  0.0
20  1.0  0.0  0.0
21  1.0  0.0  0.0
      boy   kilo   yas
0   130.0   30.0  10.0
1   125.0   36.0  11.0
2   135.0   34.0  10.0
3   133.0   30.0   9.0
4   129.0   38.0  12.0
5   180.0   90.0  30.0
6   190.0   80.0  25.0
7   175.0   90.0  35.0
8  

C:\Users\emreb\AppData\Local\Temp\ipykernel_43856\2554884055.py:27: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  cinsiyet = corruptedData.iloc[:, -1].replace({'e': 1, 'k': 0}).values


In [10]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(s, sonuc3, test_size=0.33, random_state=0)

print(x_train)
print(x_test)
print(y_train)
print(y_test)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(x_train)
X_test = sc.fit_transform(x_test)

     fr   tr   us    boy   kilo   yas  cinsiyet
8   0.0  1.0  0.0  177.0   60.0  22.0         0
6   0.0  1.0  0.0  190.0   80.0  25.0         1
16  1.0  0.0  0.0  193.0   90.0   NaN         1
4   0.0  1.0  0.0  129.0   38.0  12.0         1
2   0.0  1.0  0.0  135.0   34.0  10.0         0
5   0.0  1.0  0.0  180.0   90.0  30.0         1
17  1.0  0.0  0.0  187.0   80.0  27.0         1
9   0.0  0.0  1.0  185.0  105.0  33.0         1
7   0.0  1.0  0.0  175.0   90.0  35.0         1
18  1.0  0.0  0.0  183.0   88.0  28.0         1
3   0.0  1.0  0.0  133.0   30.0   9.0         0
0   0.0  1.0  0.0  130.0   30.0  10.0         1
15  1.0  0.0  0.0  174.0   70.0  47.0         1
12  0.0  0.0  1.0  160.0   58.0   NaN         0
     fr   tr   us    boy  kilo   yas  cinsiyet
20  1.0  0.0  0.0  164.0  66.0  32.0         0
10  0.0  0.0  1.0  165.0  55.0  27.0         0
14  0.0  0.0  1.0  167.0  62.0  55.0         0
13  0.0  0.0  1.0  162.0  59.0  41.0         0
1   0.0  1.0  0.0  125.0  36.0  11.0         

In [11]:
print(X_train)
print(X_test)

[[-0.63245553  0.8660254  -0.40824829  0.45049444 -0.29657884 -0.17552416
  -1.58113883]
 [-0.63245553  0.8660254  -0.40824829  1.00824945  0.5096549   0.08776208
   0.63245553]
 [ 1.58113883 -1.15470054 -0.40824829  1.13696215  0.91277178         nan
   0.63245553]
 [-0.63245553  0.8660254  -0.40824829 -1.6089087  -1.18343596 -1.05314493
   0.63245553]
 [-0.63245553  0.8660254  -0.40824829 -1.35148331 -1.34468271 -1.22866909
  -1.58113883]
 [-0.63245553  0.8660254  -0.40824829  0.57920713  0.91277178  0.52657247
   0.63245553]
 [ 1.58113883 -1.15470054 -0.40824829  0.87953676  0.5096549   0.26328623
   0.63245553]
 [-0.63245553 -1.15470054  2.44948974  0.79372829  1.51744708  0.7898587
   0.63245553]
 [-0.63245553  0.8660254  -0.40824829  0.36468597  0.91277178  0.96538285
   0.63245553]
 [ 1.58113883 -1.15470054 -0.40824829  0.70791983  0.8321484   0.35104831
   0.63245553]
 [-0.63245553  0.8660254  -0.40824829 -1.43729177 -1.50592946 -1.31643117
  -1.58113883]
 [-0.63245553  0.86602